---

<% if ENV['KITCHEN_DRIVER'] == 'docker' %>
driver:
  name: docker
  use_sudo: false

platforms:
  - name: debian-9
    driver_config:
      privileged: true
      run_command: /bin/systemd
  - name: ubuntu-16.04
    driver_config:
      privileged: true
      run_command: /sbin/init
  - name: ubuntu-18.04
    driver_config:
      privileged: true
      run_command: /sbin/init
  - name: centos-6
  - name: centos-7
    driver_config:
      privileged: true
      run_command: /usr/sbin/init
<% else %>
driver:
  name: vagrant
platforms:
    - name: centos-6
    - name: centos-7
<% end %>


provisioner:
  name: salt_solo
  formula: '.'
  is_file_root: true
  local_salt_root: '.'
  pillars-from-files:
    sensu2.sls: pillar/pillar.example
  pillars:
    top.sls:
      base:
        "*":
          - sensu2
  state_top:
    base:
      "*":
        - sensu2
        - sensu2-agent


suites:
  - name: default

