---

<% if ENV['KITCHEN_DRIVER'] == 'docker' %>
driver:
  name: docker
  use_sudo: false

platforms:
  - name: debian-9.3
    driver_config:
      privileged: true
      run_command: /bin/systemd
  - name: ubuntu-16.04
    driver_config:
      privileged: true
      run_command: /sbin/init
  - name: centos-6.8
  - name: centos-7.3
    driver_config:
      privileged: true
      run_command: /usr/sbin/init
<% else %>
driver:
  name: vagrant
platforms:
    - name: centos-6.9
    - name: centos-7.3
<% end %>


provisioner:
  name: salt_solo
  formula: sensu2
  pillars-from-files:
    sensu2.sls: pillar.example
  pillars:
    top.sls:
      base:
        "*":
          - sensu2 
  state_top:
    base:
      "*":
        - sensu2


suites:
  - name: default

